backend:
  name: github
  branch: new2 # Branch to update (optional; defaults to master)
  repo: barsa23/astrofy #replace with your githu repo

  publish mode: editorial_workflow

  squash_merges: true
  open_authoring: true

  publish_mode: editorial_workflow

  site_url: "https://frolicking-croquembouche-d45585.netlify.app/" # your site name

  # These lines should *not* be indented
media_folder: "src/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/PostLayout.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}